"""Prime the database

Revision ID: 3d773023dbc9
Revises: 
Create Date: 2019-03-31 00:57:57.449231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d773023dbc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=25), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('OneTime', 'Weekly', 'BiWeekly', 'Monthly', 'Quarterly', 'SemiAnually', 'Yearly', name='billtype'), nullable=False),
        sa.Column('householdId', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=25), nullable=False),
        sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['householdId'], ['households.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_householdId'), 'bills', ['householdId'], unique=False)
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('displayName', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=60), nullable=False),
        sa.Column('password', sa.String(length=254), nullable=False),
        sa.Column('registered', sa.DateTime(timezone=True), nullable=False),
        sa.Column('role', sa.String(length=10), nullable=False),
        sa.Column('householdId', sa.Integer(), nullable=True),
        sa.Column('householdCreator', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['householdId'], ['households.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_householdId'), 'users', ['householdId'], unique=False)
    op.create_table('billing_cycles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('billId', sa.Integer(), nullable=False),
        sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('startDate', sa.Date(), nullable=False),
        sa.Column('endDate', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['billId'], ['bills.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('billId', sa.Integer(), nullable=False),
        sa.Column('billCycleId', sa.Integer(), nullable=False),
        sa.Column('userId', sa.Integer(), nullable=True),
        sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['billCycleId'], ['billing_cycles.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['billId'], ['bills.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['userId'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('householdId', sa.Integer(), nullable=True),
        sa.Column('fromUserId', sa.Integer(), nullable=True),
        sa.Column('toUserId', sa.Integer(), nullable=True),
        sa.Column('sendTime', sa.DateTime(), nullable=False),
        sa.Column('message', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['fromUserId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['householdId'], ['households.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['toUserId'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invitations_fromUserId'), 'household_invitations', ['fromUserId'], unique=False)
    op.create_index(op.f('ix_household_invitations_householdId'), 'household_invitations', ['householdId'], unique=False)
    op.create_index(op.f('ix_household_invitations_toUserId'), 'household_invitations', ['toUserId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import text
    conn = op.get_bind()
    conn.execute(text("SET FOREIGN_KEY_CHECKS=0;"))

    op.drop_table('household_invitations')

    op.drop_table('bill_payments')
    op.drop_table('billing_cycles')

    op.drop_table('users')
    op.drop_table('bills')
    op.drop_table('households')
    conn.execute(text("SET FOREIGN_KEY_CHECKS=1;"))
    # ### end Alembic commands ###
