"""Inserting test data.  (No Downgrade)

Revision ID: 6d2fa998b1ea
Revises: 3d773023dbc9
Create Date: 2019-03-31 14:29:18.071519

"""
from alembic import op
import sqlalchemy as sa
from roomiez_server import models


# revision identifiers, used by Alembic.
revision = '6d2fa998b1ea'
down_revision = '3d773023dbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import os
    if 'PYTEST_CURRENT_TEST' in os.environ:
        return

    from werkzeug.security import generate_password_hash
    from datetime import datetime, timezone

    def ts(timestamp):
        return datetime.fromisoformat(timestamp).astimezone(timezone.utc)

    WE3 = 1
    op.bulk_insert(models.Household.__table__, [
        {
            'id': WE3,
            'name': 'We3',
            'created': datetime.utcnow()
        }
    ])
    PW = 'P@ssw0rd'

    ADMIN = 1
    WESLEY = 2
    TRIXIA = 3
    VERONICA = 4
    op.bulk_insert(models.User.__table__, [
        {
            'id': ADMIN,
            'displayName': 'Admin',
            'email': 'Admin@roomiez.ca',
            'password': generate_password_hash(PW),
            'role': 'admin',
            'registered': datetime.utcnow(),
            'householdId': None,
            'householdCreator': False,
        },
        {
            'id': WESLEY,
            'displayName': 'Wesley',
            'email': 'Wesley@roomiez.ca',
            'password': generate_password_hash(PW),
            'role': 'admin',
            'registered': datetime.utcnow(),
            'householdId': WE3,
            'householdCreator': True,
        },
        {
            'id': TRIXIA,
            'displayName': 'Trixia',
            'email': 'Trixia@roomiez.ca',
            'password': generate_password_hash(PW),
            'role': 'user',
            'registered': datetime.utcnow(),
            'householdId': WE3,
            'householdCreator': False,
        },
        {
            'id': VERONICA,
            'displayName': 'Veronica',
            'email': 'Veronica@roomiez.ca',
            'password': generate_password_hash(PW),
            'role': 'user',
            'registered': datetime.utcnow(),
            'householdId': WE3,
            'householdCreator': False,
        },
    ])

    RENT = 1
    UTILITIES = 2
    INTERNET = 3
    op.bulk_insert(models.Bill.__table__, [
        {
            'id': RENT,
            'type': 'Monthly',
            'householdId': WE3,
            'name': 'Rent',
            'cost': '1399.44',
            'date': ts('2017-08-01T00:00:00-05:00')
        },
        {
            'id': UTILITIES,
            'type': 'Monthly',
            'householdId': WE3,
            'name': 'Utilities',
            'cost': '550.77',
            'date': ts('2017-08-01T00:00:00-05:00')
        },
        {
            'id': INTERNET,
            'type': 'Monthly',
            'householdId': WE3,
            'name': 'Internet',
            'cost': '75.00',
            'date': ts('2017-08-15T00:00:00-05:00')
        },
    ])

    op.bulk_insert(models.BillingCycle.__table__, [
        {
            'id': 1,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2017, 8, 1),
            'endDate': datetime(2017, 8, 31),
        },
        {
            'id': 2,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2017, 8, 1),
            'endDate': datetime(2017, 8, 31),
        },
        {
            'id': 3,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2017, 8, 15),
            'endDate': datetime(2017, 9, 14),
        },

        {
            'id': 4,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2017, 9, 1),
            'endDate': datetime(2017, 9, 30),
        },
        {
            'id': 5,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2017, 9, 1),
            'endDate': datetime(2017, 9, 30),
        },
        {
            'id': 6,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2017, 9, 15),
            'endDate': datetime(2017, 10, 14),
        },

        {
            'id': 7,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2017, 10, 1),
            'endDate': datetime(2017, 10, 31),
        },
        {
            'id': 8,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2017, 10, 1),
            'endDate': datetime(2017, 10, 31),
        },
        {
            'id': 9,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2017, 10, 15),
            'endDate': datetime(2017, 11, 14),
        },

        {
            'id': 10,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2017, 11, 1),
            'endDate': datetime(2017, 11, 30),
        },
        {
            'id': 11,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2017, 11, 1),
            'endDate': datetime(2017, 11, 30),
        },
        {
            'id': 12,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2017, 11, 15),
            'endDate': datetime(2017, 12, 14),
        },

        {
            'id': 13,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2017, 12, 1),
            'endDate': datetime(2017, 12, 31),
        },
        {
            'id': 14,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2017, 12, 1),
            'endDate': datetime(2017, 12, 31),
        },
        {
            'id': 15,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2017, 12, 15),
            'endDate': datetime(2018, 1, 14),
        },

        {
            'id': 16,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 1, 1),
            'endDate': datetime(2018, 1, 31),
        },
        {
            'id': 17,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 1, 1),
            'endDate': datetime(2018, 1, 31),
        },
        {
            'id': 18,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 1, 15),
            'endDate': datetime(2018, 2, 14),
        },

        {
            'id': 19,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 2, 1),
            'endDate': datetime(2018, 2, 28),
        },
        {
            'id': 20,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 2, 1),
            'endDate': datetime(2018, 2, 28),
        },
        {
            'id': 21,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 2, 15),
            'endDate': datetime(2018, 3, 14),
        },

        {
            'id': 22,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 3, 1),
            'endDate': datetime(2018, 3, 31),
        },
        {
            'id': 23,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 3, 1),
            'endDate': datetime(2018, 3, 31),
        },
        {
            'id': 24,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 3, 15),
            'endDate': datetime(2018, 4, 14),
        },

        {
            'id': 25,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 4, 1),
            'endDate': datetime(2018, 4, 30),
        },
        {
            'id': 26,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 4, 1),
            'endDate': datetime(2018, 4, 30),
        },
        {
            'id': 27,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 4, 15),
            'endDate': datetime(2018, 5, 14),
        },

        {
            'id': 28,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 5, 1),
            'endDate': datetime(2018, 5, 31),
        },
        {
            'id': 29,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 5, 1),
            'endDate': datetime(2018, 5, 31),
        },
        {
            'id': 30,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 5, 15),
            'endDate': datetime(2018, 6, 14),
        },

        {
            'id': 31,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 6, 1),
            'endDate': datetime(2018, 6, 30),
        },
        {
            'id': 32,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 6, 1),
            'endDate': datetime(2018, 6, 30),
        },
        {
            'id': 33,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 6, 15),
            'endDate': datetime(2018, 7, 14),
        },

        {
            'id': 34,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 7, 1),
            'endDate': datetime(2018, 7, 31),
        },
        {
            'id': 35,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 7, 1),
            'endDate': datetime(2018, 7, 31),
        },
        {
            'id': 36,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 7, 15),
            'endDate': datetime(2018, 8, 14),
        },

        {
            'id': 37,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 8, 1),
            'endDate': datetime(2018, 8, 31),
        },
        {
            'id': 38,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 8, 1),
            'endDate': datetime(2018, 8, 31),
        },
        {
            'id': 39,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 8, 15),
            'endDate': datetime(2018, 9, 14),
        },

        {
            'id': 40,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 9, 1),
            'endDate': datetime(2018, 9, 30),
        },
        {
            'id': 41,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 9, 1),
            'endDate': datetime(2018, 9, 30),
        },
        {
            'id': 42,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 9, 15),
            'endDate': datetime(2018, 10, 14),
        },

        {
            'id': 43,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 10, 1),
            'endDate': datetime(2018, 10, 31),
        },
        {
            'id': 44,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 10, 1),
            'endDate': datetime(2018, 10, 31),
        },
        {
            'id': 45,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 10, 15),
            'endDate': datetime(2018, 11, 14),
        },

        {
            'id': 46,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 11, 1),
            'endDate': datetime(2018, 11, 30),
        },
        {
            'id': 47,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 11, 1),
            'endDate': datetime(2018, 11, 30),
        },
        {
            'id': 48,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 11, 15),
            'endDate': datetime(2018, 12, 14),
        },

        {
            'id': 49,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2018, 12, 1),
            'endDate': datetime(2018, 12, 31),
        },
        {
            'id': 50,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2018, 12, 1),
            'endDate': datetime(2018, 12, 31),
        },
        {
            'id': 51,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2018, 12, 15),
            'endDate': datetime(2019, 1, 14),
        },

        {
            'id': 52,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2019, 1, 1),
            'endDate': datetime(2019, 1, 31),
        },
        {
            'id': 53,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2019, 1, 1),
            'endDate': datetime(2019, 1, 31),
        },
        {
            'id': 54,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2019, 1, 15),
            'endDate': datetime(2019, 2, 14),
        },

        {
            'id': 55,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2019, 2, 1),
            'endDate': datetime(2019, 2, 28),
        },
        {
            'id': 56,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2019, 2, 1),
            'endDate': datetime(2019, 2, 28),
        },
        {
            'id': 57,
            'cost': '75.00',
            'billId': INTERNET,
            'startDate': datetime(2019, 2, 15),
            'endDate': datetime(2019, 3, 14),
        },

        {
            'id': 58,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2019, 3, 1),
            'endDate': datetime(2019, 3, 31),
        },
        {
            'id': 59,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2019, 3, 1),
            'endDate': datetime(2019, 3, 31),
        },
        {
            'id': 60,
            'cost': '75.00',
            'billId': INTERNET,
            'startDate': datetime(2019, 3, 15),
            'endDate': datetime(2019, 4, 14),
        },

        {
            'id': 61,
            'billId': RENT,
            'cost': '1399.44',
            'startDate': datetime(2019, 4, 1),
            'endDate': datetime(2019, 4, 30),
        },
        {
            'id': 62,
            'billId': UTILITIES,
            'cost': '550.77',
            'startDate': datetime(2019, 4, 1),
            'endDate': datetime(2019, 4, 30),
        },
        {
            'id': 63,
            'billId': INTERNET,
            'cost': '75.00',
            'startDate': datetime(2019, 4, 15),
            'endDate': datetime(2019, 5, 14),
        },
    ])

    op.bulk_insert(models.BillPayment.__table__, [
        {
            'billId': RENT,
            'billCycleId': 1,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 1,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 1,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 2,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 2,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 2,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2017-08-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 3,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2017-08-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 3,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2017-08-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 3,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2017-08-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 4,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 4,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 4,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 5,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 5,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 5,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2017-09-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 6,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2017-09-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 6,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2017-09-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 6,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2017-09-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 7,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 7,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 7,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 8,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 8,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 8,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2017-10-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 9,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2017-10-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 9,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2017-10-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 9,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2017-10-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 10,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 10,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 10,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 11,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 11,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 11,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2017-11-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 12,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2017-11-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 12,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2017-11-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 12,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2017-11-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 13,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 13,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 13,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 14,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 14,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 14,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2017-12-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 15,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2017-12-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 15,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2017-12-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 15,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2017-12-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 16,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 16,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 16,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 17,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 17,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 17,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-01-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 18,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-01-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 18,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-01-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 18,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-01-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 19,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 19,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 19,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 20,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 20,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 20,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-02-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 21,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-02-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 21,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-02-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 21,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-02-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 22,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 22,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 22,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 23,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 23,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 23,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-03-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 24,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-03-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 24,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-03-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 24,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-03-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 25,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 25,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 25,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 26,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 26,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 26,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-04-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 27,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-04-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 27,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-04-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 27,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-04-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 28,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 28,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 28,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 29,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 29,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 29,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-05-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 30,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-05-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 30,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-05-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 30,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-05-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 31,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 31,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 31,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 32,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 32,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 32,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-06-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 33,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-06-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 33,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-06-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 33,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-06-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 34,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 34,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 34,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 35,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 35,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 35,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-07-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 36,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-07-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 36,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-07-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 36,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-07-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 37,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 37,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 37,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 38,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 38,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 38,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-08-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 39,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-08-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 39,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-08-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 39,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-08-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 40,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 40,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 40,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 41,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 41,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 41,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-09-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 42,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-09-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 42,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-09-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 42,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-09-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 43,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 43,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 43,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 44,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 44,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 44,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-10-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 45,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-10-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 45,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-10-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 45,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-10-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 46,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 46,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 46,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 47,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 47,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 47,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-11-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 48,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-11-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 48,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-11-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 48,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-11-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 49,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 49,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 49,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 50,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 50,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 50,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2018-12-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 51,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2018-12-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 51,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2018-12-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 51,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2018-12-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 52,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 52,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 52,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 53,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 53,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 53,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2019-01-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 54,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2019-01-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 54,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2019-01-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 54,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2019-01-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 55,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 55,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 55,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 56,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 56,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 56,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2019-02-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 57,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2019-02-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 57,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2019-02-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 57,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2019-02-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 58,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 58,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 58,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 59,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 59,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 59,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2019-03-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 60,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2019-03-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 60,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2019-03-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 60,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2019-03-15T00:00:00-05:00'),
        },

        {
            'billId': RENT,
            'billCycleId': 61,
            'userId': WESLEY,
            'amount': '466.48',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 61,
            'userId': TRIXIA,
            'amount': '466.48',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },
        {
            'billId': RENT,
            'billCycleId': 61,
            'userId': VERONICA,
            'amount': '466.48',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },

        {
            'billId': UTILITIES,
            'billCycleId': 62,
            'userId': WESLEY,
            'amount': '183.59',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 62,
            'userId': TRIXIA,
            'amount': '183.59',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },
        {
            'billId': UTILITIES,
            'billCycleId': 62,
            'userId': VERONICA,
            'amount': '183.59',
            'timestamp': ts('2019-04-01T00:00:00-05:00'),
        },

        {
            'billId': INTERNET,
            'billCycleId': 63,
            'userId': WESLEY,
            'amount': '25.00',
            'timestamp': ts('2019-04-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 63,
            'userId': TRIXIA,
            'amount': '25.00',
            'timestamp': ts('2019-04-15T00:00:00-05:00'),
        },
        {
            'billId': INTERNET,
            'billCycleId': 63,
            'userId': VERONICA,
            'amount': '25.00',
            'timestamp': ts('2019-04-15T00:00:00-05:00'),
        },
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
